theme: jekyll-theme-tactile
# Coming-of-Age Films
#### What is a coming-of-age film?
###### It is a type of movie focused on a child or teenager's transition from childhood to young adulthood. Typically a protagonist faces a new challenge in which they begin to lose their childhood innocence.
#### Favorites:
###### - Lady Bird
###### - The Perks of Being A Wallflower
###### - Little Miss Sunshine
###### - Little Women
###### - Moonrise Kingdom
