theme: jekyll-theme-tactile
# Coming-of-Age Films
#### What is a coming-of-age film?
A coming-of-age film is a type of movie focused on a child or teenager transition from childhood to young adulthood. 
Typically a protagonist faces a new challenge in which they begin to lose their childhood innocence.
##### My favorites
1. Lady Bird 
directed by Greta Gerwig
[Lady Bird on Letterboxd](https://letterboxd.com/film/lady-bird)
[Facade](https://i.pinimg.com/originals/5b/e8/1a/5be81a229b881674352e7a42145271fa.jpg)
2. The Perks of Being A Wallflower 
directed by Stephen Chbosky
[TPOBAW on Letterboxd](https://letterboxd.com/film/the-perks-of-being-a-wallflower)
[Facade](https://i.pinimg.com/originals/5b/c1/7b/5bc17b6ef6493481921155f1932e3621.jpg)
3. Moonrise Kingdom
directed by Wes Anderson
[Moonrise Kingdom on Letterboxd](https://letterboxd.com/film/moonrise-kingdom)
[Facade](https://i.pinimg.com/originals/63/d6/15/63d615a9d439ed595f073001ae2c70d3.jpg)
4. Little Miss Sunshine
directed by Jonathan Dayton and Valerie Faris
[Little Miss Sunshine on Letterbord](https://letterboxd.com/film/little-miss-sunshine)
[Facade](https://i.pinimg.com/originals/15/6b/54/156b54b968a99336a4f7df18e1f60151.jpg)
5. Little Women
directed by Greta Gerwig
[Little Women on Letterboxd](https://letterboxd.com/film/little-women-2019)
[Facade](https://i.pinimg.com/originals/ac/f5/16/acf51645631e209d2a23f688d3cb8ddb.jpg)

____________________________________________________

**All of these movies are 5 stars so go watch them**
